### ISSUE TITLE
Cannot restore renv

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/shinyScenarioEditor#30]
When trying to restore renv packages, I get an error for the `httpuv` package, last lines: 

```
nce to `FOLDERID_LocalAppData'
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'httpuv'
* removing 'D:/Work/OSPS/Repos/shinyScenarioEditor/renv/profiles/dev/renv/staging/1/httpuv'
install of package 'httpuv' failed [error code 1]
```

When manually installing `httpuv` from CRAN, an updated version is intalled (1.6.15, lockfile has 1.6.12). Maybe update your package locally and commit updated lockfile?

**Comment by Felixmil** [comment]
@AKostiv8 can you do what Pavel suggested in your branch ?

**Comment by AKostiv8** [comment]
@Felixmil will do this evening

**Comment by AKostiv8** [comment]
@Felixmil When I upgrade the version - I have errors on my side. I will find a balance tomorrow

**Comment by AKostiv8** [comment]
@PavelBal / @Felixmil test this one branch please
https://github.com/esqLABS/shinyScenarioEditor/tree/renv-restore-issue-pavel

It works for me - hope for you as well

**Comment by PavelBal** [comment]
Yes that worked :)

**Comment by AKostiv8** [comment]
Great!
