### ISSUE TITLE
Define the input layout blueprint

### ISSUE THREAD

**Issue by Felixmil** [esqLABS/shinyScenarioEditor#6]
How should inputs be organized ?
- table (datamods)
- Separate fields

**Comment by hannaei** [comment]
The first option is the way it is currently, right? I prefer this over separate fields, as long as we add data validation.

**Comment by Felixmil** [comment]
We chose to pursue with the table layout offered by datamod. 
As it may lack of customisation features for input validation so we may revert this choice in the future.
