### ISSUE TITLE
Define the data structure

### ISSUE THREAD

**Issue by Felixmil** [esqLABS/shinyScenarioEditor#7]
The `r$data` data structure contains:
- a generic key for each excel file (`scenarios` for `Scenarios.xlsx`)
- For each key:
  - `file_path` path to the file
  - `sheets`: vector of sheet names
  - `[Sheet]`: a daframe containing the data loaded from a sheet of the excel file
  - `[Sheet]_modified`: a dataframe intialised as `[Sheet]` but where modified dataframe will be stored when changed.

Example:
```
r$data
  $Scenarios
    $file_path
    $sheets
    $Scenarios
    $Scenarios_modified
    $OutputPaths
    $OutputPaths_modified
  $Individuals
    $file_path
    $sheets
    ...
```

**Comment by Felixmil** [comment]
Maybe the dataframes should be stored one level below the sheet name:

```
r$data
  $Scenarios
    $file_path
    $sheets
    $Scenarios
      $original
      $modified
    $OutputPaths
      $original
      $modified
```

**Comment by PavelBal** [comment]
@Felixmil @AKostiv8 Is this issue still relevant?

**Comment by AKostiv8** [comment]
@PavelBal, I believe we can close this issue now that the structure has been implemented
